export enum AppErrorCodes {
  ERR_USER_PRESENT = "ERR_USER_PRESENT",
  ERR_USER_NOT_PRESENT = "ERR_USER_NOT_PRESENT",
  ERR_WRONG_PASSWORD = "ERR_WRONG_PASSWORD",
  ERR_SIGNUP_FAILED = "ERR_SIGNUP_FAILED",
  ERR_LOGIN_FAILED = "ERR_LOGIN_FAILED",
}
