export enum ApiErrorCodes {
  ERR_USER_PRESENT = "ERR_USER_PRESENT",
  ERR_USER_NOT_PRESENT = "ERR_USER_NOT_PRESENT",
  ERR_WRONG_PASSWORD = "ERR_WRONG_PASSWORD",
  ERR_SERVER_FAIL = "ERR_SERVER_FAIL",
}

export const PAGINATION_PAGE_SIZES = [10, 20, 40, 50];
